export type ProductCategory = string;

export type Product = {
  id: string;
  name: string;
  category: ProductCategory;
  subcategory?: string;
  brand: string;
  merchant: string;
  description: string;
  image: string;
  imageSource?: "seller_upload" | "approved_affiliate_source" | "merchant_feed" | "admin_curated" | "development_seed" | "placeholder";
  price: number;
  rating: number;
  affiliateUrl: string;
  sourceType?: "seller" | "affiliate" | "admin_curated" | "merchant_feed" | "development_seed";
  externalProductId?: string;
  sourceUpdatedAt?: string;
  listingCreatedAt?: string;
  model?: string;
  yearEra?: string;
  availability?: "in_stock" | "low_stock" | "out_of_stock" | "unknown";
  isTestData?: boolean;
  authenticityStatus?: "verified" | "authentic" | "pending_review" | "not_required" | "test_only";
  tags?: string[];
  searchKeywords?: string[];
  year?: number;
  metal?: string;
  karat?: string;
  weight?: string;
  chainLength?: string;
  chainWidth?: string;
  stone?: string;
  diamondType?: string;
  caratWeight?: string;
  certification?: string;
  featured: boolean;
  inStock: boolean;
};
