import type {
  AccountOrder,
  CustomerAddress,
  CustomerWishlistItem,
  MarketplaceCategory,
  MarketplaceProduct,
  ProductCondition,
  RecentlyViewedItem,
  SellerApplication,
  SellerProfile,
  SellerListingApproval,
} from "@/types/marketplace";

export const marketplaceCategoryOptions: MarketplaceCategory[] = [
  "Electronics",
  "Phones",
  "Computers",
  "Gaming",
  "Fashion",
  "Sneakers",
  "Fan Apparel",
  "Beauty",
  "Fitness",
  "Health",
  "Health & Wellness",
  "Home",
  "Home & Furniture",
  "Home Decor",
  "Dressers",
  "Mirrors",
  "Lamps",
  "Vases",
  "Garden",
  "Fruit Seeds",
  "Vegetable Seeds",
  "Herb Seeds",
  "Flower Seeds",
  "Studio",
  "Studio Equipment",
  "Music Software",
  "Collectibles",
  "Vintage Toys",
  "Wrestling Figures",
  "Wrestling Memorabilia",
  "Sports Cards",
  "Trading Cards",
  "Funko Pops",
  "Hot Wheels",
  "LEGO",
  "Comics",
  "Retro Gaming",
  "Pet Supplies",
  "Fine Jewelry",
  "Gold Chains",
  "Cuban Links",
  "Diamond Chains",
  "Necklaces",
  "Pendants",
  "Earrings",
  "Bracelets",
  "Rings",
  "Watches",
  "Luxury Jewelry",
  "Vintage Jewelry",
  "International Jewelry",
  "Handbags & Bags",
  "Luxury Handbags",
  "Designer Handbags",
  "Carrying Bags",
  "Travel Bags",
  "Backpacks",
  "Briefcases",
  "Duffel Bags",
  "Vintage Bags",
  "Collectible Bags",
];

export const productConditionOptions: ProductCondition[] = [
  "New",
  "Used",
  "Refurbished",
  "Vintage",
  "Collectible",
  "Open Box",
];

export const customerAddresses: CustomerAddress[] = [
  {
    id: "addr-1",
    label: "Primary Residence",
    fullName: "Avery Brooks",
    addressLine1: "12 Goldcrest Lane",
    addressLine2: "Suite 402",
    city: "Beverly Hills",
    state: "CA",
    postalCode: "90210",
    country: "USA",
    default: true,
  },
  {
    id: "addr-2",
    label: "Studio Loft",
    fullName: "Avery Brooks",
    addressLine1: "47 Gallery Way",
    city: "New York",
    state: "NY",
    postalCode: "10012",
    country: "USA",
    default: false,
  },
];

export const wishlistItems: CustomerWishlistItem[] = [
  {
    id: "wish-1",
    productId: "prod-101",
    title: "Vintage Leica M6",
    price: 2499,
    imageUrl: "https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "wish-2",
    productId: "prod-102",
    title: "Jordan 1 High OG",
    price: 420,
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "wish-3",
    productId: "prod-103",
    title: "Curved Floor Lamp",
    price: 289,
    imageUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
  },
];

export const recentlyViewedItems: RecentlyViewedItem[] = [
  {
    id: "recent-1",
    productId: "prod-201",
    title: "Universal Audio Apollo Twin",
    price: 899,
    imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80",
    viewedAt: "2 hours ago",
  },
  {
    id: "recent-2",
    productId: "prod-202",
    title: "North Face Summit Shell",
    price: 289,
    imageUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80",
    viewedAt: "Yesterday",
  },
  {
    id: "recent-3",
    productId: "prod-203",
    title: "Black Seed Oil Deluxe",
    price: 84,
    imageUrl: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=900&q=80",
    viewedAt: "3 days ago",
  },
];

export const orderHistory: AccountOrder[] = [
  { id: "ord-1001", orderNumber: "EMG-1001", date: "2026-07-15", total: 1299, status: "Delivered", items: 2 },
  { id: "ord-1002", orderNumber: "EMG-1002", date: "2026-07-02", total: 420, status: "Shipped", items: 1 },
  { id: "ord-1003", orderNumber: "EMG-1003", date: "2026-06-20", total: 98, status: "Processing", items: 3 },
  { id: "ord-1004", orderNumber: "EMG-1004", date: "2026-06-12", total: 267, status: "Cancelled", items: 1 },
];

export const sellerApplicationData: SellerApplication = {
  id: "app-01",
  profileId: "profile-123",
  businessName: "Velvet & Vine Studio",
  storeName: "Velvet & Vine",
  email: "seller@velvetandvine.com",
  bio: "Boutique home and lifestyle seller focused on rare finds, curated decor, and premium vintage pieces.",
  status: "Pending",
  submittedAt: "2026-08-05",
};

export const sellerProfileData: SellerProfile = {
  id: "seller-01",
  profileId: "profile-123",
  storeName: "Velvet & Vine",
  logoUrl: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=500&q=80",
  bio: "Curated home accents, vintage treasures, and high-quality design-led essentials for elevated living spaces.",
  contactEmail: "seller@velvetandvine.com",
  status: "Approved",
  createdAt: "2026-07-01",
  updatedAt: "2026-08-08",
};

export const sellerProductCatalog: MarketplaceProduct[] = [
  {
    id: "mp-01",
    sellerId: "seller-01",
    title: "Brass Floor Lamp",
    description: "Warm ambient floor lamp with a premium brass finish and linen shade.",
    category: "Home & Furniture",
    subcategory: "Lamps",
    brand: "Velvet & Vine",
    price: 289,
    compareAtPrice: 349,
    inventoryQuantity: 10,
    sku: "VVM-LAMP-001",
    condition: "New",
    shippingPrice: 18,
    freeShipping: false,
    imageUrls: ["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80"],
    featured: true,
    status: "active",
    createdAt: "2026-07-10",
    updatedAt: "2026-08-06",
  },
  {
    id: "mp-02",
    sellerId: "seller-01",
    title: "Vintage Mirror Set",
    description: "Hand-finished vintage mirror pair for entryways and gallery styling.",
    category: "Home Decor",
    subcategory: "Mirrors",
    brand: "Velvet & Vine",
    price: 420,
    compareAtPrice: 520,
    inventoryQuantity: 5,
    sku: "VVM-MIRROR-014",
    condition: "Vintage",
    shippingPrice: 26,
    freeShipping: true,
    imageUrls: ["https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=900&q=80"],
    featured: false,
    status: "active",
    createdAt: "2026-07-16",
    updatedAt: "2026-08-02",
  },
];

export const sellerApprovals: SellerListingApproval[] = [
  {
    id: "approval-1",
    sellerId: "seller-01",
    storeName: "Velvet & Vine",
    status: "Approved",
    notes: "Application reviewed and store profile approved after business verification.",
    submittedAt: "2026-08-05",
  },
  {
    id: "approval-2",
    sellerId: "seller-02",
    storeName: "Northline Audio",
    status: "Pending",
    notes: "Documents under review for tax and identity verification.",
    submittedAt: "2026-08-07",
  },
];
