import { buildCatalogRecord, catalogRecordToSearchable, type CatalogRecord } from "@/lib/catalog";

export const developmentCatalogSeed: CatalogRecord[] = [
  buildCatalogRecord({
    id: "test-dev-001",
    source: "admin_curated",
    source_id: "test-dev-001",
    title: "TEST Gold Cuban Link Chain 22 Inch",
    description: "DEVELOPMENT TEST RECORD ONLY. This is not live inventory and should be removed before production launch.",
    category: "Gold Jewelry",
    subcategory: "Gold Chains",
    brand: "Milan Gold",
    model: "Cuban-Link-22",
    seller: "DEVELOPMENT TEST ONLY",
    price: 540,
    condition: "Pre-owned",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: true,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2024,
    release_date: "2024-02-01",
    listing_created_at: "2024-02-01T00:00:00.000Z",
    tags: ["gold chain", "cuban link", "luxury jewelry", "test data"],
    search_keywords: ["gold chain", "cuban link", "gold jewelry", "chain", "test catalog"],
    jewelry: {
      metal: "18k gold",
      karat: "18k",
      weight: "16.2g",
      chain_length: "22 inch",
      chain_width: "12mm",
      stone: "none",
      diamond_type: "none",
      carat_weight: "n/a",
      certification: "not_applicable",
      country_of_origin: "test_only",
    },
    image: "https://images.unsplash.com/photo-1617038220319-276d3cfab193?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1617038220319-276d3cfab193?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-002",
    source: "admin_curated",
    source_id: "test-dev-002",
    title: "TEST Diamond Tennis Chain 18K",
    description: "DEVELOPMENT TEST RECORD ONLY. This is not live inventory.",
    category: "Diamonds",
    subcategory: "Diamond Chains",
    brand: "Velvet Stones",
    model: "Tennis-Chain-18K",
    seller: "DEVELOPMENT TEST ONLY",
    price: 1280,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: true,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2023,
    release_date: "2023-11-10",
    listing_created_at: "2023-11-10T00:00:00.000Z",
    tags: ["diamond chain", "tennis chain", "fine jewelry", "test data"],
    search_keywords: ["diamond chain", "tennis necklace", "diamond jewelry", "test catalog"],
    jewelry: {
      metal: "18k gold",
      karat: "18k",
      weight: "12.8g",
      chain_length: "18 inch",
      chain_width: "8mm",
      stone: "diamond",
      diamond_type: "round brilliant",
      carat_weight: "1.4ct",
      certification: "test_only",
      country_of_origin: "test_only",
    },
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-003",
    source: "admin_curated",
    source_id: "test-dev-003",
    title: "TEST Diamond Earrings Halo Set",
    description: "DEVELOPMENT TEST RECORD ONLY. This is not real available inventory.",
    category: "Fine Jewelry",
    subcategory: "Earrings",
    brand: "Aster & Co.",
    model: "Halo-Earrings-01",
    seller: "DEVELOPMENT TEST ONLY",
    price: 890,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2022,
    release_date: "2022-08-04",
    listing_created_at: "2022-08-04T00:00:00.000Z",
    tags: ["diamond earrings", "jewelry", "women's jewelry", "test data"],
    search_keywords: ["diamond earrings", "jewelry", "earrings", "test catalog"],
    jewelry: {
      metal: "white gold",
      karat: "14k",
      weight: "6.7g",
      chain_length: "n/a",
      chain_width: "n/a",
      stone: "diamond",
      diamond_type: "halo",
      carat_weight: "1.1ct",
      certification: "test_only",
      country_of_origin: "test_only",
    },
    image: "https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-004",
    source: "admin_curated",
    source_id: "test-dev-004",
    title: "TEST Gold Bracelet Link Set",
    description: "TEST DEVELOPMENT RECORD ONLY. Not a real listing or live inventory.",
    category: "Gold Jewelry",
    subcategory: "Bracelets",
    brand: "Bridle Gold",
    model: "Gold-Link-Bracelet",
    seller: "DEVELOPMENT TEST ONLY",
    price: 480,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2021,
    release_date: "2021-06-22",
    listing_created_at: "2021-06-22T00:00:00.000Z",
    tags: ["gold bracelet", "bracelet", "luxury jewelry", "test data"],
    search_keywords: ["gold bracelet", "bracelet", "jewelry", "test catalog"],
    jewelry: {
      metal: "14k gold",
      karat: "14k",
      weight: "9.2g",
      chain_length: "7.5 inch",
      chain_width: "10mm",
      stone: "none",
      diamond_type: "none",
      carat_weight: "n/a",
      certification: "test_only",
      country_of_origin: "test_only",
    },
    image: "https://images.unsplash.com/photo-1617038220319-276d3cfab193?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1617038220319-276d3cfab193?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-005",
    source: "admin_curated",
    source_id: "test-dev-005",
    title: "TEST Rolex-Style Watch Vintage Edition",
    description: "DEVELOPMENT TEST RECORD ONLY. This is not an actual product listing and should not be treated as available inventory.",
    category: "Watches",
    subcategory: "Luxury Watches",
    brand: "North Crest",
    model: "Vint-42",
    seller: "DEVELOPMENT TEST ONLY",
    price: 1200,
    condition: "Vintage",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: true,
    authenticity_status: "test_only",
    vintage: true,
    collectible: true,
    release_year: 1998,
    release_date: "1998-05-14",
    listing_created_at: "2024-04-10T00:00:00.000Z",
    tags: ["vintage watch", "luxury watch", "collectible", "test data"],
    search_keywords: ["watch", "vintage watch", "luxury watch", "timepiece", "test catalog"],
    image: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-006",
    source: "admin_curated",
    source_id: "test-dev-006",
    title: "TEST Signature Leather Handbag",
    description: "DEVELOPMENT TEST RECORD ONLY. No real inventory should be inferred.",
    category: "Luxury Handbags",
    subcategory: "Designer Handbags",
    brand: "Harbor & Co.",
    model: "Signature-Leather",
    seller: "DEVELOPMENT TEST ONLY",
    price: 980,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: true,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2024,
    release_date: "2024-03-18",
    listing_created_at: "2024-03-18T00:00:00.000Z",
    tags: ["handbag", "designer bag", "luxury accessories", "test data"],
    search_keywords: ["handbag", "designer bag", "luxury handbag", "carry bag", "test catalog"],
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-007",
    source: "admin_curated",
    source_id: "test-dev-007",
    title: "TEST Men’s Cologne Noir 100ml",
    description: "DEVELOPMENT TEST RECORD ONLY. No real fragrance listing should be treated as available inventory.",
    category: "Cologne",
    subcategory: "Men's Cologne",
    brand: "Noir House",
    model: "Noir-100",
    seller: "DEVELOPMENT TEST ONLY",
    price: 115,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: true,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2024,
    release_date: "2024-01-22",
    listing_created_at: "2024-01-22T00:00:00.000Z",
    tags: ["cologne", "men's fragrance", "luxury fragrance", "test data"],
    search_keywords: ["cologne", "fragrance", "men's cologne", "perfume alternative", "test catalog"],
    fragrance: {
      fragrance_name: "Noir 100ml",
      concentration: "Eau de Parfum",
      size: "100ml",
      scent_family: "woody amber",
      gender: "men",
      release_year: 2024,
      vintage: false,
    },
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-008",
    source: "admin_curated",
    source_id: "test-dev-008",
    title: "TEST Rose Silk Women’s Perfume 50ml",
    description: "DEVELOPMENT TEST RECORD ONLY. This should be treated as test data only.",
    category: "Perfume",
    subcategory: "Women’s Perfume",
    brand: "Rose Silk",
    model: "Rose-Silk-50",
    seller: "DEVELOPMENT TEST ONLY",
    price: 130,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: true,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2023,
    release_date: "2023-09-18",
    listing_created_at: "2023-09-18T00:00:00.000Z",
    tags: ["perfume", "women's fragrance", "luxury scent", "test data"],
    search_keywords: ["perfume", "women's perfume", "fragrance", "rose", "test catalog"],
    fragrance: {
      fragrance_name: "Rose Silk",
      concentration: "Eau de Toilette",
      size: "50ml",
      scent_family: "floral",
      gender: "women",
      release_year: 2023,
      vintage: false,
    },
    image: "https://images.unsplash.com/photo-1528740561666-dc2479dc08ab?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1528740561666-dc2479dc08ab?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-009",
    source: "admin_curated",
    source_id: "test-dev-009",
    title: "TEST Vintage Perfume Reserve 1978",
    description: "DEVELOPMENT TEST RECORD ONLY. Vintage fragrance search test record.",
    category: "Fragrance",
    subcategory: "Vintage Fragrance",
    brand: "Maison de Lune",
    model: "Reserve-1978",
    seller: "DEVELOPMENT TEST ONLY",
    price: 240,
    condition: "Vintage",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: true,
    authenticity_status: "test_only",
    vintage: true,
    collectible: true,
    release_year: 1978,
    release_date: "1978-09-12",
    listing_created_at: "2024-02-20T00:00:00.000Z",
    tags: ["vintage perfume", "old fragrance", "collectible scent", "test data"],
    search_keywords: ["vintage perfume", "old perfume", "fragrance", "collectible", "test catalog"],
    fragrance: {
      fragrance_name: "Reserve 1978",
      concentration: "Parfum",
      size: "75ml",
      scent_family: "oriental floral",
      gender: "unisex",
      release_year: 1978,
      vintage: true,
    },
    image: "https://images.unsplash.com/photo-1528740561666-dc2479dc08ab?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1528740561666-dc2479dc08ab?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-010",
    source: "admin_curated",
    source_id: "test-dev-010",
    title: "TEST iPhone 16 Pro Max 256GB",
    description: "DEVELOPMENT TEST RECORD ONLY. This is not an active merchant listing.",
    category: "Phones",
    subcategory: "Smartphones",
    brand: "Apple",
    model: "iPhone 16 Pro Max",
    seller: "DEVELOPMENT TEST ONLY",
    price: 1099,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: true,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2024,
    release_date: "2024-09-20",
    listing_created_at: "2024-09-20T00:00:00.000Z",
    tags: ["iphone", "apple", "phone", "smartphone", "test data"],
    search_keywords: ["iphone", "apple", "smartphone", "phone", "test catalog"],
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-011",
    source: "admin_curated",
    source_id: "test-dev-011",
    title: "TEST iPhone 12 Pro 128GB",
    description: "DEVELOPMENT TEST RECORD ONLY. Old smartphone search sample.",
    category: "Phones",
    subcategory: "Older Electronics",
    brand: "Apple",
    model: "iPhone 12 Pro",
    seller: "DEVELOPMENT TEST ONLY",
    price: 529,
    condition: "Refurbished",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2020,
    release_date: "2020-10-23",
    listing_created_at: "2024-03-11T00:00:00.000Z",
    tags: ["iphone", "apple", "older phone", "test data"],
    search_keywords: ["iphone", "apple", "mobile", "older electronics", "test catalog"],
    image: "https://images.unsplash.com/photo-1670649300003-70a1f147a131?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1670649300003-70a1f147a131?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-012",
    source: "admin_curated",
    source_id: "test-dev-012",
    title: "TEST Sony PlayStation 2 Console",
    description: "DEVELOPMENT TEST RECORD ONLY. Vintage gaming search record.",
    category: "Vintage Gaming",
    subcategory: "Retro Consoles",
    brand: "Sony",
    model: "PlayStation 2",
    seller: "DEVELOPMENT TEST ONLY",
    price: 220,
    condition: "Used",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: true,
    authenticity_status: "test_only",
    vintage: true,
    collectible: true,
    release_year: 2000,
    release_date: "2000-03-04",
    listing_created_at: "2024-05-12T00:00:00.000Z",
    tags: ["playstation", "retro console", "vintage gaming", "test data"],
    search_keywords: ["playstation", "retro console", "vintage games", "gaming", "test catalog"],
    vintage_fields: {
      platform: "PlayStation 2",
      game_title: "Console",
      manufacturer: "Sony",
      release_year: 2000,
      region: "NTSC-U",
      condition: "Used",
      sealed: false,
      complete_in_box: false,
      media_type: "Console",
      collectible_status: "collectible",
    },
    image: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-013",
    source: "admin_curated",
    source_id: "test-dev-013",
    title: "TEST Nintendo 64 Console",
    description: "DEVELOPMENT TEST RECORD ONLY. Retro gaming search record.",
    category: "Vintage Gaming",
    subcategory: "Retro Consoles",
    brand: "Nintendo",
    model: "Nintendo 64",
    seller: "DEVELOPMENT TEST ONLY",
    price: 180,
    condition: "Used",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: true,
    collectible: true,
    release_year: 1996,
    release_date: "1996-09-29",
    listing_created_at: "2024-04-15T00:00:00.000Z",
    tags: ["nintendo", "retro console", "vintage games", "test data"],
    search_keywords: ["nintendo", "retro console", "vintage games", "console", "test catalog"],
    vintage_fields: {
      platform: "Nintendo 64",
      game_title: "Console",
      manufacturer: "Nintendo",
      release_year: 1996,
      region: "US",
      condition: "Used",
      sealed: false,
      complete_in_box: false,
      media_type: "Console",
      collectible_status: "collectible",
    },
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-014",
    source: "admin_curated",
    source_id: "test-dev-014",
    title: "TEST Vintage Sonic Racing Game Cartridge",
    description: "DEVELOPMENT TEST RECORD ONLY. Vintage games search sample.",
    category: "Vintage Gaming",
    subcategory: "Vintage Games",
    brand: "Sega",
    model: "Sonic Riders",
    seller: "DEVELOPMENT TEST ONLY",
    price: 110,
    condition: "Complete",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: true,
    collectible: true,
    release_year: 1994,
    release_date: "1994-05-01",
    listing_created_at: "2024-07-02T00:00:00.000Z",
    tags: ["vintage games", "retro game", "carttridge", "test data"],
    search_keywords: ["vintage games", "retro games", "sonic", "sega", "test catalog"],
    vintage_fields: {
      platform: "Sega Genesis",
      game_title: "Sonic",
      manufacturer: "Sega",
      release_year: 1994,
      region: "NA",
      condition: "Complete",
      sealed: false,
      complete_in_box: true,
      media_type: "Cartridge",
      collectible_status: "collectible",
    },
    image: "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-015",
    source: "admin_curated",
    source_id: "test-dev-015",
    title: "TEST Wrestling Championship Figure",
    description: "DEVELOPMENT TEST RECORD ONLY. Wrestling collectible search sample.",
    category: "Wrestling Collectibles",
    subcategory: "Wrestling Memorabilia",
    brand: "Legacy Pro",
    model: "Title-Belt-01",
    seller: "DEVELOPMENT TEST ONLY",
    price: 210,
    condition: "Mint",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: true,
    authenticity_status: "test_only",
    vintage: false,
    collectible: true,
    release_year: 2020,
    release_date: "2020-07-20",
    listing_created_at: "2024-06-01T00:00:00.000Z",
    tags: ["wrestling", "collectible", "figure", "test data"],
    search_keywords: ["wrestling", "collectible", "figure", "memorabilia", "test catalog"],
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-016",
    source: "admin_curated",
    source_id: "test-dev-016",
    title: "TEST Vintage Wrestling Figure Collection",
    description: "DEVELOPMENT TEST RECORD ONLY. Search test for wrestling memorabilia.",
    category: "Collectibles",
    subcategory: "Vintage Toys",
    brand: "Arena Legacy",
    model: "Mat-Master-82",
    seller: "DEVELOPMENT TEST ONLY",
    price: 190,
    condition: "Vintage",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: true,
    collectible: true,
    release_year: 1987,
    release_date: "1987-01-16",
    listing_created_at: "2024-04-01T00:00:00.000Z",
    tags: ["vintage toy", "wrestling collectibles", "retro toy", "test data"],
    search_keywords: ["wrestling", "vintage toys", "collectible", "retro figure", "test catalog"],
    image: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-017",
    source: "admin_curated",
    source_id: "test-dev-017",
    title: "TEST Air Max Runner Sneakers",
    description: "DEVELOPMENT TEST RECORD ONLY. Shoe search sample.",
    category: "Sneakers",
    subcategory: "Designer Sneakers",
    brand: "North Peak",
    model: "Air-Max-Runner",
    seller: "DEVELOPMENT TEST ONLY",
    price: 170,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2024,
    release_date: "2024-06-12",
    listing_created_at: "2024-06-12T00:00:00.000Z",
    tags: ["sneakers", "sportswear", "fashion", "test data"],
    search_keywords: ["sneakers", "athletic shoes", "fashion", "test catalog"],
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-018",
    source: "admin_curated",
    source_id: "test-dev-018",
    title: "TEST Courtline Overshirt",
    description: "DEVELOPMENT TEST RECORD ONLY. Fashion search sample.",
    category: "Shirts",
    subcategory: "Button Down Shirts",
    brand: "Courtline",
    model: "Overshirt-01",
    seller: "DEVELOPMENT TEST ONLY",
    price: 120,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2023,
    release_date: "2023-10-01",
    listing_created_at: "2023-10-01T00:00:00.000Z",
    tags: ["shirt", "fashion", "apparel", "test data"],
    search_keywords: ["shirt", "overshirt", "apparel", "test catalog"],
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-019",
    source: "admin_curated",
    source_id: "test-dev-019",
    title: "TEST Luxury Accent Chair",
    description: "DEVELOPMENT TEST RECORD ONLY. Furniture search sample.",
    category: "Furniture",
    subcategory: "Living Room Furniture",
    brand: "Haven & Home",
    model: "Accent-Chair-01",
    seller: "DEVELOPMENT TEST ONLY",
    price: 590,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: true,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2024,
    release_date: "2024-05-15",
    listing_created_at: "2024-05-15T00:00:00.000Z",
    tags: ["chair", "furniture", "interior", "test data"],
    search_keywords: ["furniture", "chair", "home decor", "luxury chair", "test catalog"],
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-020",
    source: "admin_curated",
    source_id: "test-dev-020",
    title: "TEST Velvet Lounge Sofa",
    description: "DEVELOPMENT TEST RECORD ONLY. Furniture search sample.",
    category: "Furniture",
    subcategory: "Sofas",
    brand: "Haven & Home",
    model: "Lounge-Sofa-01",
    seller: "DEVELOPMENT TEST ONLY",
    price: 1299,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2023,
    release_date: "2023-12-08",
    listing_created_at: "2023-12-08T00:00:00.000Z",
    tags: ["sofa", "furniture", "living room", "test data"],
    search_keywords: ["furniture", "sofa", "living room", "test catalog"],
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-021",
    source: "admin_curated",
    source_id: "test-dev-021",
    title: "TEST Focusrite Scarlett 4i4 Studio Interface",
    description: "DEVELOPMENT TEST RECORD ONLY. Studio equipment search sample.",
    category: "Studio Equipment",
    subcategory: "Audio Interfaces",
    brand: "Focusrite",
    model: "Scarlett 4i4",
    seller: "DEVELOPMENT TEST ONLY",
    price: 229,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: true,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2024,
    release_date: "2024-01-10",
    listing_created_at: "2024-01-10T00:00:00.000Z",
    tags: ["studio equipment", "audio interface", "recording gear", "test data"],
    search_keywords: ["studio", "audio interface", "recording equipment", "test catalog"],
    image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-022",
    source: "admin_curated",
    source_id: "test-dev-022",
    title: "TEST Yamaha HS7 Studio Monitor Pair",
    description: "DEVELOPMENT TEST RECORD ONLY. Studio equipment sort test.",
    category: "Studio Equipment",
    subcategory: "Studio Monitors",
    brand: "Yamaha",
    model: "HS7",
    seller: "DEVELOPMENT TEST ONLY",
    price: 399,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2022,
    release_date: "2022-09-09",
    listing_created_at: "2022-09-09T00:00:00.000Z",
    tags: ["studio monitors", "audio", "music production", "test data"],
    search_keywords: ["studio", "monitors", "audio", "test catalog"],
    image: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-023",
    source: "admin_curated",
    source_id: "test-dev-023",
    title: "TEST Herb Seed Starter Pack",
    description: "DEVELOPMENT TEST RECORD ONLY. Garden search sample.",
    category: "Seeds",
    subcategory: "Garden Seeds",
    brand: "Root & Bloom",
    model: "Herb-Start",
    seller: "DEVELOPMENT TEST ONLY",
    price: 24,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2023,
    release_date: "2023-03-03",
    listing_created_at: "2023-03-03T00:00:00.000Z",
    tags: ["garden", "seeds", "herbs", "test data"],
    search_keywords: ["seeds", "garden", "herbs", "planting", "test catalog"],
    image: "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-024",
    source: "admin_curated",
    source_id: "test-dev-024",
    title: "TEST Vintage Vinyl Record Set",
    description: "DEVELOPMENT TEST RECORD ONLY. Vinyl category sample.",
    category: "Vinyl",
    subcategory: "Vinyl Records",
    brand: "Cinder Lane",
    model: "Vintage-Set-01",
    seller: "DEVELOPMENT TEST ONLY",
    price: 140,
    condition: "Vintage",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: true,
    collectible: true,
    release_year: 1981,
    release_date: "1981-11-18",
    listing_created_at: "2024-05-03T00:00:00.000Z",
    tags: ["vinyl", "records", "vintage music", "test data"],
    search_keywords: ["vinyl", "records", "vintage", "music", "test catalog"],
    image: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-025",
    source: "admin_curated",
    source_id: "test-dev-025",
    title: "TEST Vintage Toy Robot",
    description: "DEVELOPMENT TEST RECORD ONLY. Vintage toy sort sample.",
    category: "Vintage Toys",
    subcategory: "Vintage Toys",
    brand: "Galactic Toy Co.",
    model: "Robot-Classic",
    seller: "DEVELOPMENT TEST ONLY",
    price: 160,
    condition: "Vintage",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: true,
    collectible: true,
    release_year: 1985,
    release_date: "1985-07-14",
    listing_created_at: "2024-01-07T00:00:00.000Z",
    tags: ["vintage toy", "robot", "collectible", "test data"],
    search_keywords: ["vintage toy", "retro toy", "robot", "collectible", "test catalog"],
    image: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-026",
    source: "admin_curated",
    source_id: "test-dev-026",
    title: "TEST Vintage Handbag 1989",
    description: "DEVELOPMENT TEST RECORD ONLY. Vintage fashion sample.",
    category: "Vintage Fashion",
    subcategory: "Vintage Handbags",
    brand: "Modera",
    model: "Retro-Handbag-89",
    seller: "DEVELOPMENT TEST ONLY",
    price: 440,
    condition: "Vintage",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: true,
    authenticity_status: "test_only",
    vintage: true,
    collectible: true,
    release_year: 1989,
    release_date: "1989-05-01",
    listing_created_at: "2024-06-16T00:00:00.000Z",
    tags: ["vintage handbag", "vintage fashion", "collectible bag", "test data"],
    search_keywords: ["handbag", "vintage handbag", "fashion", "test catalog"],
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-027",
    source: "admin_curated",
    source_id: "test-dev-027",
    title: "TEST Porsche Mini Speaker System",
    description: "DEVELOPMENT TEST RECORD ONLY. Electronics search sample.",
    category: "Electronics",
    subcategory: "Audio Equipment",
    brand: "Aural Studio",
    model: "Mini-Speaker-01",
    seller: "DEVELOPMENT TEST ONLY",
    price: 340,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2021,
    release_date: "2021-08-08",
    listing_created_at: "2021-08-08T00:00:00.000Z",
    tags: ["electronics", "speaker", "audio", "test data"],
    search_keywords: ["audio", "electronics", "speaker", "test catalog"],
    image: "https://images.unsplash.com/photo-1518444065439-e933c06ce9cd?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1518444065439-e933c06ce9cd?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-028",
    source: "admin_curated",
    source_id: "test-dev-028",
    title: "TEST MacBook Air M2 13 inch",
    description: "DEVELOPMENT TEST RECORD ONLY. Current electronics search sample.",
    category: "Computers",
    subcategory: "Laptops",
    brand: "Apple",
    model: "MacBook Air M2",
    seller: "DEVELOPMENT TEST ONLY",
    price: 1349,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: true,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2022,
    release_date: "2022-06-24",
    listing_created_at: "2022-06-24T00:00:00.000Z",
    tags: ["macbook", "apple", "laptop", "computer", "test data"],
    search_keywords: ["apple", "macbook", "laptop", "computer", "test catalog"],
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-029",
    source: "admin_curated",
    source_id: "test-dev-029",
    title: "TEST Sony Walkman Cassette Player",
    description: "DEVELOPMENT TEST RECORD ONLY. Older electronics search sample.",
    category: "Vintage Electronics",
    subcategory: "Classic Audio",
    brand: "Sony",
    model: "Walkman WM-EX150",
    seller: "DEVELOPMENT TEST ONLY",
    price: 180,
    condition: "Vintage",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: true,
    collectible: true,
    release_year: 1997,
    release_date: "1997-08-01",
    listing_created_at: "2024-04-20T00:00:00.000Z",
    tags: ["walkman", "classic audio", "vintage electronics", "test data"],
    search_keywords: ["walkman", "classic audio", "vintage electronics", "test catalog"],
    image: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-030",
    source: "admin_curated",
    source_id: "test-dev-030",
    title: "TEST Pokémon Trading Card Booster Box",
    description: "DEVELOPMENT TEST RECORD ONLY. Trading cards category sample.",
    category: "Trading Cards",
    subcategory: "Collectible Cards",
    brand: "Pokémon",
    model: "Booster-Box-2023",
    seller: "DEVELOPMENT TEST ONLY",
    price: 110,
    condition: "Sealed",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: false,
    collectible: true,
    release_year: 2023,
    release_date: "2023-06-01",
    listing_created_at: "2023-06-01T00:00:00.000Z",
    tags: ["trading cards", "collectible", "pokemon", "test data"],
    search_keywords: ["trading cards", "pokemon", "collectibles", "test catalog"],
    image: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-031",
    source: "admin_curated",
    source_id: "test-dev-031",
    title: "TEST Gold Ring Statement Band",
    description: "DEVELOPMENT TEST RECORD ONLY. Jewelry search sample.",
    category: "Gold Jewelry",
    subcategory: "Rings",
    brand: "Solstice Gold",
    model: "Statement-Band",
    seller: "DEVELOPMENT TEST ONLY",
    price: 620,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2024,
    release_date: "2024-02-05",
    listing_created_at: "2024-02-05T00:00:00.000Z",
    tags: ["gold ring", "jewelry", "luxury ring", "test data"],
    search_keywords: ["gold ring", "ring", "jewelry", "test catalog"],
    jewelry: {
      metal: "18k gold",
      karat: "18k",
      weight: "8.5g",
      chain_length: "n/a",
      chain_width: "n/a",
      stone: "none",
      diamond_type: "none",
      carat_weight: "n/a",
      certification: "test_only",
      country_of_origin: "test_only",
    },
    image: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1602173574767-37ac01994b2a?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-032",
    source: "admin_curated",
    source_id: "test-dev-032",
    title: "TEST Vintage Fragrance Collector Set",
    description: "DEVELOPMENT TEST RECORD ONLY. Fragrance and vintage search sample.",
    category: "Fragrance",
    subcategory: "Vintage Fragrance",
    brand: "Maison de Lune",
    model: "Collector-Set-71",
    seller: "DEVELOPMENT TEST ONLY",
    price: 310,
    condition: "Vintage",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: true,
    collectible: true,
    release_year: 1971,
    release_date: "1971-10-12",
    listing_created_at: "2024-07-01T00:00:00.000Z",
    tags: ["vintage perfume", "fragrance set", "collectible", "test data"],
    search_keywords: ["vintage perfume", "fragrance", "gift set", "collectible", "test catalog"],
    fragrance: {
      fragrance_name: "Collector Set 1971",
      concentration: "Parfum",
      size: "100ml",
      scent_family: "amber oriental",
      gender: "unisex",
      release_year: 1971,
      vintage: true,
    },
    image: "https://images.unsplash.com/photo-1528740561666-dc2479dc08ab?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1528740561666-dc2479dc08ab?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-033",
    source: "admin_curated",
    source_id: "test-dev-033",
    title: "TEST Leather Carry Tote",
    description: "DEVELOPMENT TEST RECORD ONLY. Handbag and carry bag sample.",
    category: "Bags",
    subcategory: "Totes",
    brand: "Harbor & Co.",
    model: "Carry-Tote-01",
    seller: "DEVELOPMENT TEST ONLY",
    price: 260,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2024,
    release_date: "2024-07-19",
    listing_created_at: "2024-07-19T00:00:00.000Z",
    tags: ["bag", "carry tote", "fashion accessory", "test data"],
    search_keywords: ["bag", "carry tote", "handbag", "fashion", "test catalog"],
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-034",
    source: "admin_curated",
    source_id: "test-dev-034",
    title: "TEST Wellness Greens Starter Kit",
    description: "DEVELOPMENT TEST RECORD ONLY. Health category sample.",
    category: "Health & Wellness",
    subcategory: "Supplements",
    brand: "True Bloom",
    model: "Greens-Kit",
    seller: "DEVELOPMENT TEST ONLY",
    price: 82,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2024,
    release_date: "2024-08-04",
    listing_created_at: "2024-08-04T00:00:00.000Z",
    tags: ["wellness", "health", "supplements", "test data"],
    search_keywords: ["wellness", "health", "supplement", "test catalog"],
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-035",
    source: "admin_curated",
    source_id: "test-dev-035",
    title: "TEST Vintage Club Chair",
    description: "DEVELOPMENT TEST RECORD ONLY. Vintage furniture sample.",
    category: "Vintage Furniture",
    subcategory: "Retro Furniture",
    brand: "Oak & Lark",
    model: "Club-Chair-68",
    seller: "DEVELOPMENT TEST ONLY",
    price: 560,
    condition: "Vintage",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: true,
    collectible: false,
    release_year: 1968,
    release_date: "1968-08-16",
    listing_created_at: "2024-06-10T00:00:00.000Z",
    tags: ["vintage furniture", "chair", "retro design", "test data"],
    search_keywords: ["vintage furniture", "chair", "retro design", "home decor", "test catalog"],
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-036",
    source: "admin_curated",
    source_id: "test-dev-036",
    title: "TEST Modern Marble Console Table",
    description: "DEVELOPMENT TEST RECORD ONLY. Home decor and furniture sample.",
    category: "Home Decor",
    subcategory: "Tables",
    brand: "Stone & Curve",
    model: "Marble-Console",
    seller: "DEVELOPMENT TEST ONLY",
    price: 760,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2024,
    release_date: "2024-03-19",
    listing_created_at: "2024-03-19T00:00:00.000Z",
    tags: ["console table", "home decor", "furniture", "test data"],
    search_keywords: ["console table", "home decor", "furniture", "table", "test catalog"],
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-037",
    source: "admin_curated",
    source_id: "test-dev-037",
    title: "TEST Garden Seed Variety Pack",
    description: "DEVELOPMENT TEST RECORD ONLY. Garden and seeds sample.",
    category: "Garden",
    subcategory: "Seeds",
    brand: "Root & Bloom",
    model: "Variety-Pack-01",
    seller: "DEVELOPMENT TEST ONLY",
    price: 28,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2024,
    release_date: "2024-04-02",
    listing_created_at: "2024-04-02T00:00:00.000Z",
    tags: ["seeds", "garden", "planting", "test data"],
    search_keywords: ["seeds", "garden", "planting", "test catalog"],
    image: "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-038",
    source: "admin_curated",
    source_id: "test-dev-038",
    title: "TEST Rare Comic Volume 1",
    description: "DEVELOPMENT TEST RECORD ONLY. Comic and collectible sample.",
    category: "Comics",
    subcategory: "Collectible Comics",
    brand: "North Ink",
    model: "Volume-1-01",
    seller: "DEVELOPMENT TEST ONLY",
    price: 140,
    condition: "Near Mint",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: true,
    collectible: true,
    release_year: 1982,
    release_date: "1982-03-20",
    listing_created_at: "2024-04-11T00:00:00.000Z",
    tags: ["comics", "collectible", "vintage", "test data"],
    search_keywords: ["comics", "collectibles", "vintage", "test catalog"],
    image: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-039",
    source: "admin_curated",
    source_id: "test-dev-039",
    title: "TEST Pet Supply Grooming Kit",
    description: "DEVELOPMENT TEST RECORD ONLY. Other category sample.",
    category: "Pet Supplies",
    subcategory: "Pet Care",
    brand: "Paw & Nest",
    model: "Grooming-Kit",
    seller: "DEVELOPMENT TEST ONLY",
    price: 58,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2023,
    release_date: "2023-11-16",
    listing_created_at: "2023-11-16T00:00:00.000Z",
    tags: ["pet supplies", "care", "pet", "test data"],
    search_keywords: ["pet supplies", "pet care", "grooming", "test catalog"],
    image: "https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
  buildCatalogRecord({
    id: "test-dev-040",
    source: "admin_curated",
    source_id: "test-dev-040",
    title: "TEST Flight Deck Leather Watch",
    description: "DEVELOPMENT TEST RECORD ONLY. Luxury watch search sample.",
    category: "Watches",
    subcategory: "Luxury Watches",
    brand: "Flight Deck",
    model: "Leather-Deck",
    seller: "DEVELOPMENT TEST ONLY",
    price: 680,
    condition: "New",
    availability: "unknown",
    in_stock: false,
    active: true,
    featured: false,
    authenticity_status: "test_only",
    vintage: false,
    collectible: false,
    release_year: 2024,
    release_date: "2024-06-28",
    listing_created_at: "2024-06-28T00:00:00.000Z",
    tags: ["watch", "luxury", "leather", "test data"],
    search_keywords: ["watch", "luxury watch", "timepiece", "test catalog"],
    image: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=900&q=80",
    images: ["https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=900&q=80"],
    is_test_data: true,
    status: "active",
  }),
];

export function getDevelopmentCatalogDocuments() {
  return developmentCatalogSeed
    .filter((record) => record.is_test_data && record.active)
    .map((record) => catalogRecordToSearchable(record));
}
